### ISSUE TITLE
Enhancement Requests

### ISSUE THREAD

**Issue by a12288** [amotolani/fmc_collections#5]
Hi, Amotolani

I am using yours collection to migrate our ASA to FTD and hope you can make 2 improvements which will surely benefits my migration and others as well.

1. Can you allow to use Port Group as destination ports in acp_rule.py? For some access rules with a large number of reusable destination ports, this enhancement will save us lots of time.
2. Somehow, the options of send-event-to-fmc, log_end, log_start, and enable_log did not work for me, not sure, it's my part or not.

Appreciate in advance your time on this.

Leo

**Comment by amotolani** [comment]
Hello @a12288 

On 1
I made an update to add the enhance you requested [here](https://github.com/amotolani/fmc_collections/pull/6)

Basically the new feature is available in [release-1.1.3](https://galaxy.ansible.com/amotolani/cisco_fmc).

With this you can specify an addition option that adds groups in the `source_port_groups` and `destination_port_groups` fields. I hope you find it useful.

On 2
Maybe we need to get more information to figure that one out.

I will closing the issue now. You can open another if you have more information on item 2

Cheers !!
